title: UMN RKT Avionics Documentation
description: Documentation for the UMN RKT Avionics project
theme: just-the-docs

url: https://UMN-Rocket-Team.github.io/avionics-docs

aux_links:
  Template Repository: https://github.com/UMN-Rocket-Team/avionics-docs
